url: "http://stephania07.github.io/" # the base hostname & protocol for your site
baseurl: "" 

# Site settings
title: Stephania Iyob
email: stephaniaiyob@yahoo.com
description: "When you want something all the universe conspires in helping you to achieve it. Paulo Coelho"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Stephania Iyob
  pic: 1
  position: Full-Stack Developer
  social:
    - title: twitter
      url: EleniyobElen
    - title: github
      url: https://github.com/stephania07
   
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: EleniyobElen
  # - title: facebook
  #   url:
  - title: github
    url: https://github.com/stephania07

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty