# Site settings
title: Stephania Iyob
highlighter: rouge
email: stephaniaiyob@yahoo.com
description: When you want something all the universe conspires in helping you to achieve it. Paulo Coelho  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stephania07.github.io/" # the base hostname & protocol for your site
twitter_username: EleniyobElen
github_username:  stephania07

# Build settings
markdown: kramdown
